/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:aec4a7cb3a56373a4de56c5c71e966ce:3d85c382947f3d556588951abee998f1:7776c10cf51089ac9560b2fb64f1143a$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class TexturePacker
	{
		public const string Bullet = "bullet";
		public const string JadeRabbit = "jadeRabbit";
		public const string JadeRabbitFull = "jadeRabbitFull";
		public const string JadeRabbitTiny = "jadeRabbitTiny";
	}
}