/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:37c2798f9eba38ded72d4b0a4e9dad55:1fbf11f4e0f5b6ae1969a6f0f676513c:7776c10cf51089ac9560b2fb64f1143a$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class Element
	{
		public const string Destiny_DragonsBreath_item = "Destiny/DragonsBreath/item";
		public const string Destiny_DragonsBreath_popup = "Destiny/DragonsBreath/popup";
		public const string Destiny_Gjallarhorn_item = "Destiny/Gjallarhorn/item";
		public const string Destiny_Gjallarhorn_popup = "Destiny/Gjallarhorn/popup";
		public const string Destiny_HardLight_item = "Destiny/HardLight/item";
		public const string Destiny_HardLight_popup = "Destiny/HardLight/popup";
		public const string Destiny_Hawkmoon_item = "Destiny/Hawkmoon/item";
		public const string Destiny_Hawkmoon_popup = "Destiny/Hawkmoon/popup";
		public const string Destiny_Icebreaker_item = "Destiny/Icebreaker/item";
		public const string Destiny_Icebreaker_popup = "Destiny/Icebreaker/popup";
		public const string Destiny_JadeRabbette_item = "Destiny/JadeRabbette/item";
		public const string Destiny_JadeRabbette_popup = "Destiny/JadeRabbette/popup";
		public const string Destiny_JadeRabbit_item = "Destiny/JadeRabbit/item";
		public const string Destiny_JadeRabbit_popup = "Destiny/JadeRabbit/popup";
		public const string Destiny_LastWord_item = "Destiny/LastWord/item";
		public const string Destiny_LastWord_popup = "Destiny/LastWord/popup";
		public const string Destiny_MonteCarlo_item = "Destiny/MonteCarlo/item";
		public const string Destiny_MonteCarlo_popup = "Destiny/MonteCarlo/popup";
		public const string Destiny_NLB_item = "Destiny/NLB/item";
		public const string Destiny_NLB_popup = "Destiny/NLB/popup";
		public const string Destiny_RedDeath_item = "Destiny/RedDeath/item";
		public const string Destiny_RedDeath_popup = "Destiny/RedDeath/popup";
		public const string Destiny_Regime_item = "Destiny/Regime/item";
		public const string Destiny_Regime_popup = "Destiny/Regime/popup";
		public const string Destiny_Stranger_item = "Destiny/Stranger/item";
		public const string Destiny_Stranger_popup = "Destiny/Stranger/popup";
		public const string Destiny_Thorn_item = "Destiny/Thorn/item";
		public const string Destiny_Thorn_popup = "Destiny/Thorn/popup";
		public const string Destiny_UniversalRemote_item = "Destiny/UniversalRemote/item";
		public const string Destiny_UniversalRemote_popup = "Destiny/UniversalRemote/popup";
		public const string Destiny_Vex_item = "Destiny/Vex/item";
		public const string Destiny_Vex_popup = "Destiny/Vex/popup";
		public const string Female_walkDown_frame18 = "female/walkDown/frame18";
		public const string Female_walkDown_frame19 = "female/walkDown/frame19";
		public const string Female_walkDown_frame20 = "female/walkDown/frame20";
		public const string Female_walkDown_frame21 = "female/walkDown/frame21";
		public const string Female_walkDown_frame22 = "female/walkDown/frame22";
		public const string Female_walkDown_frame23 = "female/walkDown/frame23";
		public const string Female_walkDown_frame24 = "female/walkDown/frame24";
		public const string Female_walkDown_frame25 = "female/walkDown/frame25";
		public const string Female_walkDown_frame26 = "female/walkDown/frame26";
		public const string Female_walkLeft_frame9 = "female/walkLeft/frame9";
		public const string Female_walkLeft_frame10 = "female/walkLeft/frame10";
		public const string Female_walkLeft_frame11 = "female/walkLeft/frame11";
		public const string Female_walkLeft_frame12 = "female/walkLeft/frame12";
		public const string Female_walkLeft_frame13 = "female/walkLeft/frame13";
		public const string Female_walkLeft_frame14 = "female/walkLeft/frame14";
		public const string Female_walkLeft_frame15 = "female/walkLeft/frame15";
		public const string Female_walkLeft_frame16 = "female/walkLeft/frame16";
		public const string Female_walkLeft_frame17 = "female/walkLeft/frame17";
		public const string Female_walkRight_frame27 = "female/walkRight/frame27";
		public const string Female_walkRight_frame28 = "female/walkRight/frame28";
		public const string Female_walkRight_frame29 = "female/walkRight/frame29";
		public const string Female_walkRight_frame30 = "female/walkRight/frame30";
		public const string Female_walkRight_frame31 = "female/walkRight/frame31";
		public const string Female_walkRight_frame32 = "female/walkRight/frame32";
		public const string Female_walkRight_frame33 = "female/walkRight/frame33";
		public const string Female_walkRight_frame34 = "female/walkRight/frame34";
		public const string Female_walkRight_frame35 = "female/walkRight/frame35";
		public const string Female_walkUp_frame0 = "female/walkUp/frame0";
		public const string Female_walkUp_frame1 = "female/walkUp/frame1";
		public const string Female_walkUp_frame2 = "female/walkUp/frame2";
		public const string Female_walkUp_frame3 = "female/walkUp/frame3";
		public const string Female_walkUp_frame4 = "female/walkUp/frame4";
		public const string Female_walkUp_frame5 = "female/walkUp/frame5";
		public const string Female_walkUp_frame6 = "female/walkUp/frame6";
		public const string Female_walkUp_frame7 = "female/walkUp/frame7";
		public const string Female_walkUp_frame8 = "female/walkUp/frame8";
		public const string Gun_bullet = "Gun/bullet";
	}
}